// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
///

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBrWuYiaJaM0dyk6TH0gk0fPCXbgW2N98E',
    appId: '1:940598381936:web:cbe4a954c8312f9d4793b5',
    messagingSenderId: '940598381936',
    projectId: 'colorist-a7c4b',
    authDomain: 'colorist-a7c4b.firebaseapp.com',
    storageBucket: 'colorist-a7c4b.firebasestorage.app',
    measurementId: 'G-N68J0JZ4CH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA88le4Vd1GZTidQsIWAKidLjmYnuT7e_E',
    appId: '1:940598381936:android:153f49486c258b264793b5',
    messagingSenderId: '940598381936',
    projectId: 'colorist-a7c4b',
    storageBucket: 'colorist-a7c4b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3nsjEaCrB51QghWvCuV4lLQQEMcLCZ8E',
    appId: '1:940598381936:ios:957de3ba32656ee04793b5',
    messagingSenderId: '940598381936',
    projectId: 'colorist-a7c4b',
    storageBucket: 'colorist-a7c4b.firebasestorage.app',
    iosBundleId: 'com.example.colorist',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB3nsjEaCrB51QghWvCuV4lLQQEMcLCZ8E',
    appId: '1:940598381936:ios:957de3ba32656ee04793b5',
    messagingSenderId: '940598381936',
    projectId: 'colorist-a7c4b',
    storageBucket: 'colorist-a7c4b.firebasestorage.app',
    iosBundleId: 'com.example.colorist',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBrWuYiaJaM0dyk6TH0gk0fPCXbgW2N98E',
    appId: '1:940598381936:web:9646ed56626dadb74793b5',
    messagingSenderId: '940598381936',
    projectId: 'colorist-a7c4b',
    authDomain: 'colorist-a7c4b.firebaseapp.com',
    storageBucket: 'colorist-a7c4b.firebasestorage.app',
    measurementId: 'G-G44QZMG7MP',
  );
}
